function fdc_welc()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load fdc_welc

a = figure('Color',[0 0 0], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[177 182 450 356], ...
	'Tag','Fig1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 0.3], ...
	'Position',[28.5 219 267.75 36], ...
	'String','Welcome to the Flight Dynamics and Control Toolbox v1.3!', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'ForegroundColor',[0.9 0.9 0.9], ...
	'HorizontalAlignment','left', ...
	'Position',[7.5 47.25 330.75 155.25], ...
	'String',mat2, ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',10, ...
	'ForegroundColor',[1 0.2 0.1], ...
	'Position',[102 9.75 143.25 15], ...
	'String','<<< Press a key to continue >>>', ...
	'Style','text', ...
	'Tag','StaticText3');



%-----------------------------------------------------------------------
% The FDC toolbox. Copyright M.O. Rauw, 1994-2002. All rights reserved.
% This software is licensed under the Dutchroll Open Source Software
% License (DOSSL), version 1.0. See LICENSE.TXT in the DOC subdirectory
% for detailed information.
